export const npcCharacterAbi = [
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'getPaymentBinding',
    outputs: [
      { internalType: 'address', name: 'wallet', type: 'address' },
      { internalType: 'uint64', name: 'version', type: 'uint64' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { internalType: 'address', name: 'wallet', type: 'address' },
    ],
    name: 'bindPaymentWallet',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'clearPaymentWallet',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'exists',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextTokenId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'getNpc',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'npcName', type: 'string' },
          { internalType: 'string', name: 'metadataURI', type: 'string' },
          { internalType: 'uint8', name: 'archetype', type: 'uint8' },
          { internalType: 'uint8', name: 'riskLevel', type: 'uint8' },
          { internalType: 'uint16', name: 'level', type: 'uint16' },
          { internalType: 'uint32', name: 'reputation', type: 'uint32' },
          {
            components: [
              { internalType: 'uint16', name: 'livingNeedsWeightBps', type: 'uint16' },
              { internalType: 'uint16', name: 'reserveWeightBps', type: 'uint16' },
              { internalType: 'uint16', name: 'tradingWeightBps', type: 'uint16' },
              { internalType: 'uint64', name: 'minimumLivingBudgetUSDC', type: 'uint64' },
              { internalType: 'uint64', name: 'minimumReserveBudgetUSDC', type: 'uint64' },
              { internalType: 'uint32', name: 'rebalanceIntervalSeconds', type: 'uint32' },
              { internalType: 'uint32', name: 'chainActionCooldownSeconds', type: 'uint32' },
              { internalType: 'uint64', name: 'minTradeUSDC', type: 'uint64' },
              { internalType: 'uint64', name: 'maxTradeUSDC', type: 'uint64' },
            ],
            internalType: 'struct NpcCharacter.PortfolioConfig',
            name: 'portfolio',
            type: 'tuple',
          },
        ],
        internalType: 'struct NpcCharacter.NpcData',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const
